# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - cd hw4
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_r testthat

script: 
  - Rscript -e "library(testthat);source_dir('./',pattern='[^_][^e][^x].[rR]$',env=globalenv());z=test_dir('tests');stopifnot(sum(z$failed)==0)"

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email: false
